from dataclasses import dataclass


@dataclass
class ProductListSchema:
    name: str = "name"
    source: str = "source"
    current_price: str = "current_price"
    original_price: str = "original_price"
    discount: str = "discount"
    image: str = "image"
    description: str = "description"
    location: str = "location"
    condition: str = "condition"
    rating: str = "rating"
    reviews_count: str = "reviews_count"
    url: str = "url"
    brand: str = "brand"
    category: str = "category"
    subcategory: str = "subcategory"
    product_id: str = "product_id"


@dataclass
class ProductDetailSchema:
    name: str = "name"
    current_price: str = "current_price"
    original_price: str = "original_price"
    discount: str = "discount"
    image: str = "image"
    description: str = "description"
    location: str = "location"
    condition: str = "condition"
    rating: str = "rating"
    reviews_count: str = "reviews_count"
    url: str = "url"
    brand: str = "brand"
    category: str = "category"
    subcategory: str = "subcategory"
    product_id: str = "product_id"
    specifications: str = "specifications"
    features: str = "features"
    product_details: str = "product_details"
    product_reviews: str = "product_reviews"
    label: str = "label"
    value: str = "value"
    feature: str = "feature"
    reviews: str = "reviews"
    title: str = "title"
    comment: str = "comment"
    date: str = "date"
    author: str = "author"
    verified: str = "verified"
    product_basic_info: str = "product_basic_info"
    zoom_url: str = "zoom_url"
    alt: str = "alt"
    images: str = "images"
    source: str = "source"
    key: str = "key"
