use_default_settings: true

general:
  instance_name: 'searxng'
  debug: false
  enable_metrics: true

server:
  secret_key: "${SEARXNG_SECRET}"
  bind_address: "0.0.0.0:8080"
  base_url: 'https://search.volera.app/'
  http_protocol_version: "1.1"
  method: "POST"
  default_http_headers:
    X-Content-Type-Options: nosniff
    X-XSS-Protection: 1; mode=block
    X-Frame-Options: SAMEORIGIN

search:
  safe_search: 0
  autocomplete: 'google'
  default_lang: "en"
  formats:
    - html
    - json
  retry_on_http_error: true
  max_request_timeout: 15.0

outgoing:
  request_timeout: 5.0
  max_request_timeout: 15.0
  pool_connections: 100
  pool_maxsize: 100
  enable_http2: true
  retries: 3
  proxies:
    http: ${SEARXNG_HTTP_PROXY}
    https: ${SEARXNG_HTTPS_PROXY}
  using_tor_proxy: false
  extra_proxy_timeout: 10.0
  verify: true
  max_redirects: 5
  useragent_suffix: ""
  pool_connections_timeout: 3.0

engines:
  - name: google
    engine: google
    shortcut: g
    disabled: false
    headers:
      Accept-Language: en-US,en;q=0.9
    proxies:
      http: ${SEARXNG_HTTP_PROXY}
      https: ${SEARXNG_HTTPS_PROXY}

  - name: duckduckgo
    engine: duckduckgo
    shortcut: d
    disabled: false
    headers:
      Accept-Language: en-US,en;q=0.9
    proxies:
      http: ${SEARXNG_HTTP_PROXY}
      https: ${SEARXNG_HTTPS_PROXY}

  - name: bing
    engine: bing
    shortcut: b
    disabled: false
    headers:
      Accept-Language: en-US,en;q=0.9
    proxies:
      http: ${SEARXNG_HTTP_PROXY}
      https: ${SEARXNG_HTTPS_PROXY}

  - name: wikipedia
    engine: wikipedia
    shortcut: w
    disabled: false